# https://github.com/marketplace/actions/publish-to-npm
# https://github.com/actions/setup-node/issues/52
# https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package
name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - run: npm install
      - run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
